#!/bin/sh

# Example of how to build with browserify
# You will need to `npm install browserify react-tools --save-dev` first

echo "-> Converting JSX to JS"
jsx app/ tmp/

echo "-> Building app bundle"
browserify -e tmp/main.js > public/bundle.js

echo "-> Removing tmp/"
rm -rf tmp

echo "-> Now run 'npm start', not 'script/dev'"

